apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bot.authPersistenceClaimName" . }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.auth.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.auth.persistence.size }}
